name: Eleventy Build
on: [push]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: cjerrington/actions-eleventy@master
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: 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
          publish_dir: ./public
